repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: community

  # A short description of the repository that will show up on GitHub
  description: This is the home of the developer stylechain community.

  # The branch used by default for pull requests and when the repository is cloned/viewed.
  default_branch: main

  # This repository is a template that others can use to start a new repository.
  is_template: false

collaborators:
  - username: ronilaukkarinen
    permission: admin

  - username: schalkneethling
    permission: admin

labels:
  - name: help wanted
    color: ffff54
  - name: good first issue
    color: ff8c00
  - name: chore
    color: 2f4f4f
    description: a routine task
# additional colors in this palette:
# 7f0000 , 1e90ff, ffdab9, ff69b4
